/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6b6db21c80ba9cfeb812f12bd8b8b3e4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
