import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Image from 'next/image';
import stylex from '@stylexjs/stylex';

const styles = stylex.create({
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  footer: {
    display: 'flex',
    padding: '2rem 0',
    borderTop: '1px solid #eaeaea',
    justifyContent: 'center',
    alignItems: 'center',
    '@media (prefers-color-scheme: dark)': {
      borderTop: '1px solid #222',
    },
  },
  footerLink: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexGrow: 1,
  },
  footerLogo: {
    height: '1em',
    marginStart: '0.5rem',
  },
  footerLogoImage: {
    '@media (prefers-color-scheme: dark)': {
      filter: 'invert(1)',
    },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={stylex(styles.container)}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
        {process.env.NODE_ENV === 'development' && (
          // eslint-disable-next-line @next/next/no-css-tags
          <link href="/_next/static/styles/stylex.css" rel="stylesheet" />
        )}
      </Head>
      <Component {...pageProps} />
      <footer className={stylex(styles.footer)}>
        <a
          className={stylex(styles.footerLink)}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          rel="noopener noreferrer"
          target="_blank"
        >
          Powered by{' '}
          <span className={stylex(styles.footerLogo)}>
            <Image
              alt="Vercel Logo"
              className={stylex(styles.footerLogoImage)}
              height={16}
              src="/vercel.svg"
              width={72}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
