#!/usr/bin/env node
/**
 * Compile Tailwind theme.css to standard CSS variables
 * Run: node compile-theme.js
 */

const fs = require('fs');
const path = require('path');

async function main() {
  const { compile } = await import('tailwindcss');
  
  // Load the theme from tailwind-to-stylex
  const themePath = require.resolve('tailwind-to-stylex/theme.css');
  const theme = fs.readFileSync(themePath, 'utf-8');
  
  // Convert @theme block to :root CSS variables
  // Extract variables from @theme block
  const themeVarsMatch = theme.match(/@theme[^{]*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}/s);
  let cssVars = '';
  
  if (themeVarsMatch) {
    const themeContent = themeVarsMatch[1];
    // Extract all CSS custom property definitions
    const varMatches = themeContent.matchAll(/(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);/g);
    const vars = [];
    for (const match of varMatches) {
      vars.push(`  ${match[1]}: ${match[2].trim()};`);
    }
    
    // Extract @keyframes
    const keyframeMatches = themeContent.matchAll(/@keyframes\s+(\w+)\s*\{([^}]+\{[^}]*\}[^}]*)\}/g);
    const keyframes = [];
    for (const match of keyframeMatches) {
      keyframes.push(`@keyframes ${match[1]} {${match[2]}}`);
    }
    
    cssVars = `:root {\n${vars.join('\n')}\n}\n\n${keyframes.join('\n\n')}`;
  }
  
  // Compile preflight with theme
  const preflightPath = require.resolve('tailwindcss/preflight.css');
  const preflight = fs.readFileSync(preflightPath, 'utf-8');
  const { build: buildPreflight } = await compile(`${theme}\n\n${preflight}`);
  const preflightCss = buildPreflight([]);
  
  // Write compiled theme
  const outputPath = path.join(__dirname, 'app', 'theme.css');
  const output = `/* Compiled Tailwind Theme - Auto-generated by compile-theme.js */

/* CSS Variables */
${cssVars}

/* Preflight (Reset) */
${preflightCss}
`;
  
  fs.writeFileSync(outputPath, output);
  
  console.log(`✓ Compiled theme written to ${outputPath}`);
  console.log(`  Variables: ${cssVars.split('\n').filter(l => l.includes('--')).length}`);
  console.log(`  Total size: ${output.length} bytes`);
}

main().catch(console.error);

