/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 */

import type { Metadata } from 'next';
import * as stylex from '@stylexjs/stylex';
import './globals.css';
import { vars } from '../styles/vars.stylex';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html {...stylex.props(styles.globals)} lang="en">
      <body {...stylex.props(styles.globals, styles.body, styles.bodyFont)}>
        {children}
      </body>
    </html>
  );
}

const styles = stylex.create({
  globals: {
    maxWidth: '100vw',
    overflowX: 'hidden',
    colorScheme: 'light dark',
  },
  body: {
    color: `rgb(${vars.foregroundRGB})`,
    backgroundColor: `rgb(${vars.backgroundStartRGB})`,
    backgroundImage: `linear-gradient(to bottom, transparent, rgb(${vars.backgroundEndRGB}))`,
  },
  bodyFont: {
    fontFamily:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif',
  },
});
