// flow-typed signature: 6c26e569a05e3f354a49aaefb5202339
// flow-typed version: <<STUB>>/ansis_v^3.3.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'ansis/index' {
  declare module.exports: $Exports<'ansis'>;
}
declare module 'ansis/index.js' {
  declare module.exports: $Exports<'ansis'>;
}
