// flow-typed signature: b69de9956360e937568f76e4fe7aa840
// flow-typed version: <<STUB>>/brotli-size_v^4.0.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brotli-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brotli-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brotli-size/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brotli-size/dist/index' {
  declare module.exports: $Exports<'brotli-size/dist'>;
}
declare module 'brotli-size/dist/index.js' {
  declare module.exports: $Exports<'brotli-size/dist'>;
}
