// flow-typed signature: 77b4d42eaab1d24bb1638c183b7ecc5f
// flow-typed version: <<STUB>>/clean-css_v^5.3.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clean-css/lib/clean' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/clone' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/configuration' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/configuration/break-up' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/configuration/can-override' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/configuration/properties/understandable' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/configuration/restore' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/hack' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/invalid-property-error' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-0/optimize' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/optimize' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/background' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/border-radius' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/box-shadow' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/filter' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/font-weight' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/margin' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/outline' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/property-optimizers/padding' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/sort-selectors' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/tidy-at-rule' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/tidy-block' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/tidy-rules' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-hex' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-hsl' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-rgb' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/degrees' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/fraction' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/precision' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/starts-as-url' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/text-quotes' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/time' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/unit' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/url-prefix' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/url-quotes' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/url-whitespace' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/whitespace' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-1/value-optimizers/zero' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/extract-properties' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/is-mergeable' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/merge-adjacent' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/merge-media-queries' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/merge-non-adjacent-by-body' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/merge-non-adjacent-by-selector' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/optimize' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/every-values-pair' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/find-component-in' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/has-inherit' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/has-same-values' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/has-unset' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/is-component-of' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/is-mergeable-shorthand' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/merge-into-shorthands' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/optimize' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/override-properties' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/overrides-non-component-shorthand' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/properties/populate-components' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/reduce-non-adjacent' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/remove-duplicate-font-at-rules' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/remove-duplicate-media-queries' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/remove-duplicates' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/remove-unused-at-rules' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/reorderable' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/restore-with-components' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/restructure' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/rules-overlap' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/specificities-overlap' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/specificity' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/level-2/tidy-rule-duplicates' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/remove-unused' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/restore-from-optimizing' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/validator' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/vendor-prefixes' {
  declare module.exports: any;
}

declare module 'clean-css/lib/optimizer/wrap-for-optimizing' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/compatibility' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/fetch' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/format' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/inline-request' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/inline-timeout' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/inline' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/optimization-level' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/plugins' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/rebase-to' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/rebase' {
  declare module.exports: any;
}

declare module 'clean-css/lib/options/rounding-precision' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/apply-source-maps' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/extract-import-url-and-media' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/input-source-map-tracker' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/is-allowed-resource' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/load-original-sources' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/load-remote-resource' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/match-data-uri' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/normalize-path' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/read-sources' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/rebase-local-map' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/rebase-remote-map' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/rebase' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/restore-import' {
  declare module.exports: any;
}

declare module 'clean-css/lib/reader/rewrite-url' {
  declare module.exports: any;
}

declare module 'clean-css/lib/tokenizer/marker' {
  declare module.exports: any;
}

declare module 'clean-css/lib/tokenizer/token' {
  declare module.exports: any;
}

declare module 'clean-css/lib/tokenizer/tokenize' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/clone-array' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/format-position' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/has-protocol' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/is-data-uri-resource' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/is-http-resource' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/is-https-resource' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/is-import' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/is-remote-resource' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/natural-compare' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/override' {
  declare module.exports: any;
}

declare module 'clean-css/lib/utils/split' {
  declare module.exports: any;
}

declare module 'clean-css/lib/writer/helpers' {
  declare module.exports: any;
}

declare module 'clean-css/lib/writer/one-time' {
  declare module.exports: any;
}

declare module 'clean-css/lib/writer/simple' {
  declare module.exports: any;
}

declare module 'clean-css/lib/writer/source-maps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clean-css/index' {
  declare module.exports: $Exports<'clean-css'>;
}
declare module 'clean-css/index.js' {
  declare module.exports: $Exports<'clean-css'>;
}
declare module 'clean-css/lib/clean.js' {
  declare module.exports: $Exports<'clean-css/lib/clean'>;
}
declare module 'clean-css/lib/optimizer/clone.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/clone'>;
}
declare module 'clean-css/lib/optimizer/configuration.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/configuration'>;
}
declare module 'clean-css/lib/optimizer/configuration/break-up.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/configuration/break-up'>;
}
declare module 'clean-css/lib/optimizer/configuration/can-override.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/configuration/can-override'>;
}
declare module 'clean-css/lib/optimizer/configuration/properties/understandable.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/configuration/properties/understandable'>;
}
declare module 'clean-css/lib/optimizer/configuration/restore.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/configuration/restore'>;
}
declare module 'clean-css/lib/optimizer/hack.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/hack'>;
}
declare module 'clean-css/lib/optimizer/invalid-property-error.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/invalid-property-error'>;
}
declare module 'clean-css/lib/optimizer/level-0/optimize.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-0/optimize'>;
}
declare module 'clean-css/lib/optimizer/level-1/optimize.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/optimize'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/background.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/background'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/border-radius.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/border-radius'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/box-shadow.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/box-shadow'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/filter.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/filter'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/font-weight.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/font-weight'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/margin.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/margin'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/outline.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/outline'>;
}
declare module 'clean-css/lib/optimizer/level-1/property-optimizers/padding.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/property-optimizers/padding'>;
}
declare module 'clean-css/lib/optimizer/level-1/sort-selectors.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/sort-selectors'>;
}
declare module 'clean-css/lib/optimizer/level-1/tidy-at-rule.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/tidy-at-rule'>;
}
declare module 'clean-css/lib/optimizer/level-1/tidy-block.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/tidy-block'>;
}
declare module 'clean-css/lib/optimizer/level-1/tidy-rules.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/tidy-rules'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/color'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-hex.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-hex'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-hsl.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-hsl'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-rgb.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/color/shorten-rgb'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/degrees.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/degrees'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/fraction.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/fraction'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/precision.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/precision'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/starts-as-url.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/starts-as-url'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/text-quotes.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/text-quotes'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/time.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/time'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/unit.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/unit'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/url-prefix.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/url-prefix'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/url-quotes.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/url-quotes'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/url-whitespace.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/url-whitespace'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/whitespace.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/whitespace'>;
}
declare module 'clean-css/lib/optimizer/level-1/value-optimizers/zero.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-1/value-optimizers/zero'>;
}
declare module 'clean-css/lib/optimizer/level-2/extract-properties.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/extract-properties'>;
}
declare module 'clean-css/lib/optimizer/level-2/is-mergeable.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/is-mergeable'>;
}
declare module 'clean-css/lib/optimizer/level-2/merge-adjacent.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/merge-adjacent'>;
}
declare module 'clean-css/lib/optimizer/level-2/merge-media-queries.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/merge-media-queries'>;
}
declare module 'clean-css/lib/optimizer/level-2/merge-non-adjacent-by-body.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/merge-non-adjacent-by-body'>;
}
declare module 'clean-css/lib/optimizer/level-2/merge-non-adjacent-by-selector.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/merge-non-adjacent-by-selector'>;
}
declare module 'clean-css/lib/optimizer/level-2/optimize.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/optimize'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/every-values-pair.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/every-values-pair'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/find-component-in.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/find-component-in'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/has-inherit.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/has-inherit'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/has-same-values.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/has-same-values'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/has-unset.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/has-unset'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/is-component-of.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/is-component-of'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/is-mergeable-shorthand.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/is-mergeable-shorthand'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/merge-into-shorthands.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/merge-into-shorthands'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/optimize.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/optimize'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/override-properties.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/override-properties'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/overrides-non-component-shorthand.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/overrides-non-component-shorthand'>;
}
declare module 'clean-css/lib/optimizer/level-2/properties/populate-components.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/properties/populate-components'>;
}
declare module 'clean-css/lib/optimizer/level-2/reduce-non-adjacent.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/reduce-non-adjacent'>;
}
declare module 'clean-css/lib/optimizer/level-2/remove-duplicate-font-at-rules.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/remove-duplicate-font-at-rules'>;
}
declare module 'clean-css/lib/optimizer/level-2/remove-duplicate-media-queries.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/remove-duplicate-media-queries'>;
}
declare module 'clean-css/lib/optimizer/level-2/remove-duplicates.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/remove-duplicates'>;
}
declare module 'clean-css/lib/optimizer/level-2/remove-unused-at-rules.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/remove-unused-at-rules'>;
}
declare module 'clean-css/lib/optimizer/level-2/reorderable.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/reorderable'>;
}
declare module 'clean-css/lib/optimizer/level-2/restore-with-components.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/restore-with-components'>;
}
declare module 'clean-css/lib/optimizer/level-2/restructure.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/restructure'>;
}
declare module 'clean-css/lib/optimizer/level-2/rules-overlap.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/rules-overlap'>;
}
declare module 'clean-css/lib/optimizer/level-2/specificities-overlap.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/specificities-overlap'>;
}
declare module 'clean-css/lib/optimizer/level-2/specificity.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/specificity'>;
}
declare module 'clean-css/lib/optimizer/level-2/tidy-rule-duplicates.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/level-2/tidy-rule-duplicates'>;
}
declare module 'clean-css/lib/optimizer/remove-unused.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/remove-unused'>;
}
declare module 'clean-css/lib/optimizer/restore-from-optimizing.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/restore-from-optimizing'>;
}
declare module 'clean-css/lib/optimizer/validator.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/validator'>;
}
declare module 'clean-css/lib/optimizer/vendor-prefixes.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/vendor-prefixes'>;
}
declare module 'clean-css/lib/optimizer/wrap-for-optimizing.js' {
  declare module.exports: $Exports<'clean-css/lib/optimizer/wrap-for-optimizing'>;
}
declare module 'clean-css/lib/options/compatibility.js' {
  declare module.exports: $Exports<'clean-css/lib/options/compatibility'>;
}
declare module 'clean-css/lib/options/fetch.js' {
  declare module.exports: $Exports<'clean-css/lib/options/fetch'>;
}
declare module 'clean-css/lib/options/format.js' {
  declare module.exports: $Exports<'clean-css/lib/options/format'>;
}
declare module 'clean-css/lib/options/inline-request.js' {
  declare module.exports: $Exports<'clean-css/lib/options/inline-request'>;
}
declare module 'clean-css/lib/options/inline-timeout.js' {
  declare module.exports: $Exports<'clean-css/lib/options/inline-timeout'>;
}
declare module 'clean-css/lib/options/inline.js' {
  declare module.exports: $Exports<'clean-css/lib/options/inline'>;
}
declare module 'clean-css/lib/options/optimization-level.js' {
  declare module.exports: $Exports<'clean-css/lib/options/optimization-level'>;
}
declare module 'clean-css/lib/options/plugins.js' {
  declare module.exports: $Exports<'clean-css/lib/options/plugins'>;
}
declare module 'clean-css/lib/options/rebase-to.js' {
  declare module.exports: $Exports<'clean-css/lib/options/rebase-to'>;
}
declare module 'clean-css/lib/options/rebase.js' {
  declare module.exports: $Exports<'clean-css/lib/options/rebase'>;
}
declare module 'clean-css/lib/options/rounding-precision.js' {
  declare module.exports: $Exports<'clean-css/lib/options/rounding-precision'>;
}
declare module 'clean-css/lib/reader/apply-source-maps.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/apply-source-maps'>;
}
declare module 'clean-css/lib/reader/extract-import-url-and-media.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/extract-import-url-and-media'>;
}
declare module 'clean-css/lib/reader/input-source-map-tracker.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/input-source-map-tracker'>;
}
declare module 'clean-css/lib/reader/is-allowed-resource.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/is-allowed-resource'>;
}
declare module 'clean-css/lib/reader/load-original-sources.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/load-original-sources'>;
}
declare module 'clean-css/lib/reader/load-remote-resource.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/load-remote-resource'>;
}
declare module 'clean-css/lib/reader/match-data-uri.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/match-data-uri'>;
}
declare module 'clean-css/lib/reader/normalize-path.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/normalize-path'>;
}
declare module 'clean-css/lib/reader/read-sources.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/read-sources'>;
}
declare module 'clean-css/lib/reader/rebase-local-map.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/rebase-local-map'>;
}
declare module 'clean-css/lib/reader/rebase-remote-map.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/rebase-remote-map'>;
}
declare module 'clean-css/lib/reader/rebase.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/rebase'>;
}
declare module 'clean-css/lib/reader/restore-import.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/restore-import'>;
}
declare module 'clean-css/lib/reader/rewrite-url.js' {
  declare module.exports: $Exports<'clean-css/lib/reader/rewrite-url'>;
}
declare module 'clean-css/lib/tokenizer/marker.js' {
  declare module.exports: $Exports<'clean-css/lib/tokenizer/marker'>;
}
declare module 'clean-css/lib/tokenizer/token.js' {
  declare module.exports: $Exports<'clean-css/lib/tokenizer/token'>;
}
declare module 'clean-css/lib/tokenizer/tokenize.js' {
  declare module.exports: $Exports<'clean-css/lib/tokenizer/tokenize'>;
}
declare module 'clean-css/lib/utils/clone-array.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/clone-array'>;
}
declare module 'clean-css/lib/utils/format-position.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/format-position'>;
}
declare module 'clean-css/lib/utils/has-protocol.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/has-protocol'>;
}
declare module 'clean-css/lib/utils/is-data-uri-resource.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/is-data-uri-resource'>;
}
declare module 'clean-css/lib/utils/is-http-resource.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/is-http-resource'>;
}
declare module 'clean-css/lib/utils/is-https-resource.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/is-https-resource'>;
}
declare module 'clean-css/lib/utils/is-import.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/is-import'>;
}
declare module 'clean-css/lib/utils/is-remote-resource.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/is-remote-resource'>;
}
declare module 'clean-css/lib/utils/natural-compare.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/natural-compare'>;
}
declare module 'clean-css/lib/utils/override.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/override'>;
}
declare module 'clean-css/lib/utils/split.js' {
  declare module.exports: $Exports<'clean-css/lib/utils/split'>;
}
declare module 'clean-css/lib/writer/helpers.js' {
  declare module.exports: $Exports<'clean-css/lib/writer/helpers'>;
}
declare module 'clean-css/lib/writer/one-time.js' {
  declare module.exports: $Exports<'clean-css/lib/writer/one-time'>;
}
declare module 'clean-css/lib/writer/simple.js' {
  declare module.exports: $Exports<'clean-css/lib/writer/simple'>;
}
declare module 'clean-css/lib/writer/source-maps.js' {
  declare module.exports: $Exports<'clean-css/lib/writer/source-maps'>;
}
