// flow-typed signature: 2698d714a88a0bfdf172d2bb579b7c77
// flow-typed version: <<STUB>>/css-shorthand-expand_v^1.2.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-shorthand-expand'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-shorthand-expand' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-shorthand-expand/source/background' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/border-radius' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/border' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/directional' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/font' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/is-color' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/is-length' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/normalize-color' {
  declare module.exports: any;
}

declare module 'css-shorthand-expand/source/outline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-shorthand-expand/source/background.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/background'>;
}
declare module 'css-shorthand-expand/source/border-radius.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/border-radius'>;
}
declare module 'css-shorthand-expand/source/border.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/border'>;
}
declare module 'css-shorthand-expand/source/directional.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/directional'>;
}
declare module 'css-shorthand-expand/source/font.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/font'>;
}
declare module 'css-shorthand-expand/source/index' {
  declare module.exports: $Exports<'css-shorthand-expand/source'>;
}
declare module 'css-shorthand-expand/source/index.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source'>;
}
declare module 'css-shorthand-expand/source/is-color.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/is-color'>;
}
declare module 'css-shorthand-expand/source/is-length.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/is-length'>;
}
declare module 'css-shorthand-expand/source/normalize-color.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/normalize-color'>;
}
declare module 'css-shorthand-expand/source/outline.js' {
  declare module.exports: $Exports<'css-shorthand-expand/source/outline'>;
}
