// flow-typed signature: 65bc810cf4fb56f75a9310caa6c583e8
// flow-typed version: <<STUB>>/css-mediaquery_v^0.1.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-mediaquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-mediaquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'css-mediaquery/index' {
  declare module.exports: $Exports<'css-mediaquery'>;
}
declare module 'css-mediaquery/index.js' {
  declare module.exports: $Exports<'css-mediaquery'>;
}
