// flow-typed signature: 112af2a2d2ee9988440db5413b856722
// flow-typed version: <<STUB>>/css-loader_v^7.1.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'css-loader/dist' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/postcss-icss-parser' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/postcss-import-parser' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/postcss-url-parser' {
  declare module.exports: any;
}

declare module 'css-loader/dist/runtime/api' {
  declare module.exports: any;
}

declare module 'css-loader/dist/runtime/getUrl' {
  declare module.exports: any;
}

declare module 'css-loader/dist/runtime/noSourceMaps' {
  declare module.exports: any;
}

declare module 'css-loader/dist/runtime/sourceMaps' {
  declare module.exports: any;
}

declare module 'css-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-loader/dist/cjs.js' {
  declare module.exports: $Exports<'css-loader/dist/cjs'>;
}
declare module 'css-loader/dist/index' {
  declare module.exports: $Exports<'css-loader/dist'>;
}
declare module 'css-loader/dist/index.js' {
  declare module.exports: $Exports<'css-loader/dist'>;
}
declare module 'css-loader/dist/plugins/index' {
  declare module.exports: $Exports<'css-loader/dist/plugins'>;
}
declare module 'css-loader/dist/plugins/index.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins'>;
}
declare module 'css-loader/dist/plugins/postcss-icss-parser.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/postcss-icss-parser'>;
}
declare module 'css-loader/dist/plugins/postcss-import-parser.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/postcss-import-parser'>;
}
declare module 'css-loader/dist/plugins/postcss-url-parser.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/postcss-url-parser'>;
}
declare module 'css-loader/dist/runtime/api.js' {
  declare module.exports: $Exports<'css-loader/dist/runtime/api'>;
}
declare module 'css-loader/dist/runtime/getUrl.js' {
  declare module.exports: $Exports<'css-loader/dist/runtime/getUrl'>;
}
declare module 'css-loader/dist/runtime/noSourceMaps.js' {
  declare module.exports: $Exports<'css-loader/dist/runtime/noSourceMaps'>;
}
declare module 'css-loader/dist/runtime/sourceMaps.js' {
  declare module.exports: $Exports<'css-loader/dist/runtime/sourceMaps'>;
}
declare module 'css-loader/dist/utils.js' {
  declare module.exports: $Exports<'css-loader/dist/utils'>;
}
