// flow-typed signature: a9c251dd3be45994c0ddde7675d5a422
// flow-typed version: <<STUB>>/esbuild_v^0.25.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esbuild'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esbuild' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esbuild/install' {
  declare module.exports: any;
}

declare module 'esbuild/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esbuild/install.js' {
  declare module.exports: $Exports<'esbuild/install'>;
}
declare module 'esbuild/lib/main.js' {
  declare module.exports: $Exports<'esbuild/lib/main'>;
}
