// flow-typed signature: 2102ef05a4844826d10916a368731e1a
// flow-typed version: <<STUB>>/fast-glob_v^3.3.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-glob/out' {
  declare module.exports: any;
}

declare module 'fast-glob/out/managers/tasks' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/async' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/filters/deep' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/filters/entry' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/filters/error' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/matchers/matcher' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/matchers/partial' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/provider' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/stream' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/sync' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/transformers/entry' {
  declare module.exports: any;
}

declare module 'fast-glob/out/readers/async' {
  declare module.exports: any;
}

declare module 'fast-glob/out/readers/reader' {
  declare module.exports: any;
}

declare module 'fast-glob/out/readers/stream' {
  declare module.exports: any;
}

declare module 'fast-glob/out/readers/sync' {
  declare module.exports: any;
}

declare module 'fast-glob/out/settings' {
  declare module.exports: any;
}

declare module 'fast-glob/out/types' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/array' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/errno' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/fs' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/path' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/pattern' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/stream' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-glob/out/index' {
  declare module.exports: $Exports<'fast-glob/out'>;
}
declare module 'fast-glob/out/index.js' {
  declare module.exports: $Exports<'fast-glob/out'>;
}
declare module 'fast-glob/out/managers/tasks.js' {
  declare module.exports: $Exports<'fast-glob/out/managers/tasks'>;
}
declare module 'fast-glob/out/providers/async.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/async'>;
}
declare module 'fast-glob/out/providers/filters/deep.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/filters/deep'>;
}
declare module 'fast-glob/out/providers/filters/entry.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/filters/entry'>;
}
declare module 'fast-glob/out/providers/filters/error.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/filters/error'>;
}
declare module 'fast-glob/out/providers/matchers/matcher.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/matchers/matcher'>;
}
declare module 'fast-glob/out/providers/matchers/partial.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/matchers/partial'>;
}
declare module 'fast-glob/out/providers/provider.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/provider'>;
}
declare module 'fast-glob/out/providers/stream.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/stream'>;
}
declare module 'fast-glob/out/providers/sync.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/sync'>;
}
declare module 'fast-glob/out/providers/transformers/entry.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/transformers/entry'>;
}
declare module 'fast-glob/out/readers/async.js' {
  declare module.exports: $Exports<'fast-glob/out/readers/async'>;
}
declare module 'fast-glob/out/readers/reader.js' {
  declare module.exports: $Exports<'fast-glob/out/readers/reader'>;
}
declare module 'fast-glob/out/readers/stream.js' {
  declare module.exports: $Exports<'fast-glob/out/readers/stream'>;
}
declare module 'fast-glob/out/readers/sync.js' {
  declare module.exports: $Exports<'fast-glob/out/readers/sync'>;
}
declare module 'fast-glob/out/settings.js' {
  declare module.exports: $Exports<'fast-glob/out/settings'>;
}
declare module 'fast-glob/out/types/index' {
  declare module.exports: $Exports<'fast-glob/out/types'>;
}
declare module 'fast-glob/out/types/index.js' {
  declare module.exports: $Exports<'fast-glob/out/types'>;
}
declare module 'fast-glob/out/utils/array.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/array'>;
}
declare module 'fast-glob/out/utils/errno.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/errno'>;
}
declare module 'fast-glob/out/utils/fs.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/fs'>;
}
declare module 'fast-glob/out/utils/index' {
  declare module.exports: $Exports<'fast-glob/out/utils'>;
}
declare module 'fast-glob/out/utils/index.js' {
  declare module.exports: $Exports<'fast-glob/out/utils'>;
}
declare module 'fast-glob/out/utils/path.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/path'>;
}
declare module 'fast-glob/out/utils/pattern.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/pattern'>;
}
declare module 'fast-glob/out/utils/stream.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/stream'>;
}
declare module 'fast-glob/out/utils/string.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/string'>;
}
