// flow-typed signature: b7db45c16cf45231708b77e615fa85da
// flow-typed version: <<STUB>>/fb-watchman_v^2.0.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fb-watchman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fb-watchman' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'fb-watchman/index' {
  declare module.exports: $Exports<'fb-watchman'>;
}
declare module 'fb-watchman/index.js' {
  declare module.exports: $Exports<'fb-watchman'>;
}
