// flow-typed signature: 8074cd6384abbdffe832dae7d181a47c
// flow-typed version: <<STUB>>/is-glob_v^4.0.3/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'is-glob/index' {
  declare module.exports: $Exports<'is-glob'>;
}
declare module 'is-glob/index.js' {
  declare module.exports: $Exports<'is-glob'>;
}
