// flow-typed signature: 9292ca0b8e8e45277b62191745102a53
// flow-typed version: <<STUB>>/next_v14.2.21/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next' {
  declare module.exports: any;
}
