// flow-typed signature: 6f4c37230a581c2bcc5608945fbfc535
// flow-typed version: <<STUB>>/playwright_v^1.55.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'playwright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'playwright' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'playwright/cli' {
  declare module.exports: any;
}

declare module 'playwright/jsx-runtime' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/config' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/configLoader' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/esmLoaderHost' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/expectBundle' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/expectBundleImpl' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/fixtures' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/globals' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/ipc' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/poolBuilder' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/process' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/suiteUtils' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/test' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/testLoader' {
  declare module.exports: any;
}

declare module 'playwright/lib/common/testType' {
  declare module.exports: any;
}

declare module 'playwright/lib/fsWatcher' {
  declare module.exports: any;
}

declare module 'playwright/lib' {
  declare module.exports: any;
}

declare module 'playwright/lib/internalsForTest' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/events' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/folders' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/stringInternPool' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/teleReceiver' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/teleSuiteUpdater' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/testServerConnection' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/testServerInterface' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/testTree' {
  declare module.exports: any;
}

declare module 'playwright/lib/isomorphic/types.d' {
  declare module.exports: any;
}

declare module 'playwright/lib/loader/loaderMain' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/expect' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/matcherHint' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/matchers' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/toBeTruthy' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/toEqual' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/toHaveURL' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/toMatchAriaSnapshot' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/toMatchSnapshot' {
  declare module.exports: any;
}

declare module 'playwright/lib/matchers/toMatchText' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/bundle' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/exports' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/inProcessTransport' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/proxyBackend' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/server' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/tool' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcp/transport' {
  declare module.exports: any;
}

declare module 'playwright/lib/mcpBundleImpl' {
  declare module.exports: any;
}

declare module 'playwright/lib/plugins/gitCommitInfoPlugin' {
  declare module.exports: any;
}

declare module 'playwright/lib/plugins' {
  declare module.exports: any;
}

declare module 'playwright/lib/plugins/webServerPlugin' {
  declare module.exports: any;
}

declare module 'playwright/lib/program' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/base' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/blob' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/dot' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/empty' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/github' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/html' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/internalReporter' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/json' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/junit' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/line' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/list' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/listModeReporter' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/markdown' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/merge' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/multiplexer' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/reporterV2' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/teleEmitter' {
  declare module.exports: any;
}

declare module 'playwright/lib/reporters/versions/blobV1' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/dispatcher' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/failureTracker' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/lastRun' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/loaderHost' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/loadUtils' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/processHost' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/projectUtils' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/rebase' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/reporters' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/sigIntWatcher' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/taskRunner' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/tasks' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/testGroups' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/testRunner' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/testServer' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/uiModeReporter' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/vcs' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/watchMode' {
  declare module.exports: any;
}

declare module 'playwright/lib/runner/workerHost' {
  declare module.exports: any;
}

declare module 'playwright/lib/third_party/pirates' {
  declare module.exports: any;
}

declare module 'playwright/lib/third_party/tsconfig-loader' {
  declare module.exports: any;
}

declare module 'playwright/lib/transform/babelBundle' {
  declare module.exports: any;
}

declare module 'playwright/lib/transform/babelBundleImpl' {
  declare module.exports: any;
}

declare module 'playwright/lib/transform/compilationCache' {
  declare module.exports: any;
}

declare module 'playwright/lib/transform/esmLoader' {
  declare module.exports: any;
}

declare module 'playwright/lib/transform/portTransport' {
  declare module.exports: any;
}

declare module 'playwright/lib/transform/transform' {
  declare module.exports: any;
}

declare module 'playwright/lib/util' {
  declare module.exports: any;
}

declare module 'playwright/lib/utilsBundle' {
  declare module.exports: any;
}

declare module 'playwright/lib/utilsBundleImpl' {
  declare module.exports: any;
}

declare module 'playwright/lib/worker/fixtureRunner' {
  declare module.exports: any;
}

declare module 'playwright/lib/worker/testInfo' {
  declare module.exports: any;
}

declare module 'playwright/lib/worker/testTracing' {
  declare module.exports: any;
}

declare module 'playwright/lib/worker/timeoutManager' {
  declare module.exports: any;
}

declare module 'playwright/lib/worker/util' {
  declare module.exports: any;
}

declare module 'playwright/lib/worker/workerMain' {
  declare module.exports: any;
}

declare module 'playwright/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'playwright/cli.js' {
  declare module.exports: $Exports<'playwright/cli'>;
}
declare module 'playwright/index' {
  declare module.exports: $Exports<'playwright'>;
}
declare module 'playwright/index.js' {
  declare module.exports: $Exports<'playwright'>;
}
declare module 'playwright/jsx-runtime.js' {
  declare module.exports: $Exports<'playwright/jsx-runtime'>;
}
declare module 'playwright/lib/common/config.js' {
  declare module.exports: $Exports<'playwright/lib/common/config'>;
}
declare module 'playwright/lib/common/configLoader.js' {
  declare module.exports: $Exports<'playwright/lib/common/configLoader'>;
}
declare module 'playwright/lib/common/esmLoaderHost.js' {
  declare module.exports: $Exports<'playwright/lib/common/esmLoaderHost'>;
}
declare module 'playwright/lib/common/expectBundle.js' {
  declare module.exports: $Exports<'playwright/lib/common/expectBundle'>;
}
declare module 'playwright/lib/common/expectBundleImpl.js' {
  declare module.exports: $Exports<'playwright/lib/common/expectBundleImpl'>;
}
declare module 'playwright/lib/common/fixtures.js' {
  declare module.exports: $Exports<'playwright/lib/common/fixtures'>;
}
declare module 'playwright/lib/common/globals.js' {
  declare module.exports: $Exports<'playwright/lib/common/globals'>;
}
declare module 'playwright/lib/common/ipc.js' {
  declare module.exports: $Exports<'playwright/lib/common/ipc'>;
}
declare module 'playwright/lib/common/poolBuilder.js' {
  declare module.exports: $Exports<'playwright/lib/common/poolBuilder'>;
}
declare module 'playwright/lib/common/process.js' {
  declare module.exports: $Exports<'playwright/lib/common/process'>;
}
declare module 'playwright/lib/common/suiteUtils.js' {
  declare module.exports: $Exports<'playwright/lib/common/suiteUtils'>;
}
declare module 'playwright/lib/common/test.js' {
  declare module.exports: $Exports<'playwright/lib/common/test'>;
}
declare module 'playwright/lib/common/testLoader.js' {
  declare module.exports: $Exports<'playwright/lib/common/testLoader'>;
}
declare module 'playwright/lib/common/testType.js' {
  declare module.exports: $Exports<'playwright/lib/common/testType'>;
}
declare module 'playwright/lib/fsWatcher.js' {
  declare module.exports: $Exports<'playwright/lib/fsWatcher'>;
}
declare module 'playwright/lib/index' {
  declare module.exports: $Exports<'playwright/lib'>;
}
declare module 'playwright/lib/index.js' {
  declare module.exports: $Exports<'playwright/lib'>;
}
declare module 'playwright/lib/internalsForTest.js' {
  declare module.exports: $Exports<'playwright/lib/internalsForTest'>;
}
declare module 'playwright/lib/isomorphic/events.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/events'>;
}
declare module 'playwright/lib/isomorphic/folders.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/folders'>;
}
declare module 'playwright/lib/isomorphic/stringInternPool.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/stringInternPool'>;
}
declare module 'playwright/lib/isomorphic/teleReceiver.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/teleReceiver'>;
}
declare module 'playwright/lib/isomorphic/teleSuiteUpdater.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/teleSuiteUpdater'>;
}
declare module 'playwright/lib/isomorphic/testServerConnection.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/testServerConnection'>;
}
declare module 'playwright/lib/isomorphic/testServerInterface.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/testServerInterface'>;
}
declare module 'playwright/lib/isomorphic/testTree.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/testTree'>;
}
declare module 'playwright/lib/isomorphic/types.d.js' {
  declare module.exports: $Exports<'playwright/lib/isomorphic/types.d'>;
}
declare module 'playwright/lib/loader/loaderMain.js' {
  declare module.exports: $Exports<'playwright/lib/loader/loaderMain'>;
}
declare module 'playwright/lib/matchers/expect.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/expect'>;
}
declare module 'playwright/lib/matchers/matcherHint.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/matcherHint'>;
}
declare module 'playwright/lib/matchers/matchers.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/matchers'>;
}
declare module 'playwright/lib/matchers/toBeTruthy.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/toBeTruthy'>;
}
declare module 'playwright/lib/matchers/toEqual.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/toEqual'>;
}
declare module 'playwright/lib/matchers/toHaveURL.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/toHaveURL'>;
}
declare module 'playwright/lib/matchers/toMatchAriaSnapshot.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/toMatchAriaSnapshot'>;
}
declare module 'playwright/lib/matchers/toMatchSnapshot.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/toMatchSnapshot'>;
}
declare module 'playwright/lib/matchers/toMatchText.js' {
  declare module.exports: $Exports<'playwright/lib/matchers/toMatchText'>;
}
declare module 'playwright/lib/mcp/bundle.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/bundle'>;
}
declare module 'playwright/lib/mcp/exports.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/exports'>;
}
declare module 'playwright/lib/mcp/inProcessTransport.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/inProcessTransport'>;
}
declare module 'playwright/lib/mcp/proxyBackend.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/proxyBackend'>;
}
declare module 'playwright/lib/mcp/server.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/server'>;
}
declare module 'playwright/lib/mcp/tool.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/tool'>;
}
declare module 'playwright/lib/mcp/transport.js' {
  declare module.exports: $Exports<'playwright/lib/mcp/transport'>;
}
declare module 'playwright/lib/mcpBundleImpl.js' {
  declare module.exports: $Exports<'playwright/lib/mcpBundleImpl'>;
}
declare module 'playwright/lib/plugins/gitCommitInfoPlugin.js' {
  declare module.exports: $Exports<'playwright/lib/plugins/gitCommitInfoPlugin'>;
}
declare module 'playwright/lib/plugins/index' {
  declare module.exports: $Exports<'playwright/lib/plugins'>;
}
declare module 'playwright/lib/plugins/index.js' {
  declare module.exports: $Exports<'playwright/lib/plugins'>;
}
declare module 'playwright/lib/plugins/webServerPlugin.js' {
  declare module.exports: $Exports<'playwright/lib/plugins/webServerPlugin'>;
}
declare module 'playwright/lib/program.js' {
  declare module.exports: $Exports<'playwright/lib/program'>;
}
declare module 'playwright/lib/reporters/base.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/base'>;
}
declare module 'playwright/lib/reporters/blob.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/blob'>;
}
declare module 'playwright/lib/reporters/dot.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/dot'>;
}
declare module 'playwright/lib/reporters/empty.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/empty'>;
}
declare module 'playwright/lib/reporters/github.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/github'>;
}
declare module 'playwright/lib/reporters/html.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/html'>;
}
declare module 'playwright/lib/reporters/internalReporter.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/internalReporter'>;
}
declare module 'playwright/lib/reporters/json.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/json'>;
}
declare module 'playwright/lib/reporters/junit.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/junit'>;
}
declare module 'playwright/lib/reporters/line.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/line'>;
}
declare module 'playwright/lib/reporters/list.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/list'>;
}
declare module 'playwright/lib/reporters/listModeReporter.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/listModeReporter'>;
}
declare module 'playwright/lib/reporters/markdown.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/markdown'>;
}
declare module 'playwright/lib/reporters/merge.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/merge'>;
}
declare module 'playwright/lib/reporters/multiplexer.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/multiplexer'>;
}
declare module 'playwright/lib/reporters/reporterV2.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/reporterV2'>;
}
declare module 'playwright/lib/reporters/teleEmitter.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/teleEmitter'>;
}
declare module 'playwright/lib/reporters/versions/blobV1.js' {
  declare module.exports: $Exports<'playwright/lib/reporters/versions/blobV1'>;
}
declare module 'playwright/lib/runner/dispatcher.js' {
  declare module.exports: $Exports<'playwright/lib/runner/dispatcher'>;
}
declare module 'playwright/lib/runner/failureTracker.js' {
  declare module.exports: $Exports<'playwright/lib/runner/failureTracker'>;
}
declare module 'playwright/lib/runner/lastRun.js' {
  declare module.exports: $Exports<'playwright/lib/runner/lastRun'>;
}
declare module 'playwright/lib/runner/loaderHost.js' {
  declare module.exports: $Exports<'playwright/lib/runner/loaderHost'>;
}
declare module 'playwright/lib/runner/loadUtils.js' {
  declare module.exports: $Exports<'playwright/lib/runner/loadUtils'>;
}
declare module 'playwright/lib/runner/processHost.js' {
  declare module.exports: $Exports<'playwright/lib/runner/processHost'>;
}
declare module 'playwright/lib/runner/projectUtils.js' {
  declare module.exports: $Exports<'playwright/lib/runner/projectUtils'>;
}
declare module 'playwright/lib/runner/rebase.js' {
  declare module.exports: $Exports<'playwright/lib/runner/rebase'>;
}
declare module 'playwright/lib/runner/reporters.js' {
  declare module.exports: $Exports<'playwright/lib/runner/reporters'>;
}
declare module 'playwright/lib/runner/sigIntWatcher.js' {
  declare module.exports: $Exports<'playwright/lib/runner/sigIntWatcher'>;
}
declare module 'playwright/lib/runner/taskRunner.js' {
  declare module.exports: $Exports<'playwright/lib/runner/taskRunner'>;
}
declare module 'playwright/lib/runner/tasks.js' {
  declare module.exports: $Exports<'playwright/lib/runner/tasks'>;
}
declare module 'playwright/lib/runner/testGroups.js' {
  declare module.exports: $Exports<'playwright/lib/runner/testGroups'>;
}
declare module 'playwright/lib/runner/testRunner.js' {
  declare module.exports: $Exports<'playwright/lib/runner/testRunner'>;
}
declare module 'playwright/lib/runner/testServer.js' {
  declare module.exports: $Exports<'playwright/lib/runner/testServer'>;
}
declare module 'playwright/lib/runner/uiModeReporter.js' {
  declare module.exports: $Exports<'playwright/lib/runner/uiModeReporter'>;
}
declare module 'playwright/lib/runner/vcs.js' {
  declare module.exports: $Exports<'playwright/lib/runner/vcs'>;
}
declare module 'playwright/lib/runner/watchMode.js' {
  declare module.exports: $Exports<'playwright/lib/runner/watchMode'>;
}
declare module 'playwright/lib/runner/workerHost.js' {
  declare module.exports: $Exports<'playwright/lib/runner/workerHost'>;
}
declare module 'playwright/lib/third_party/pirates.js' {
  declare module.exports: $Exports<'playwright/lib/third_party/pirates'>;
}
declare module 'playwright/lib/third_party/tsconfig-loader.js' {
  declare module.exports: $Exports<'playwright/lib/third_party/tsconfig-loader'>;
}
declare module 'playwright/lib/transform/babelBundle.js' {
  declare module.exports: $Exports<'playwright/lib/transform/babelBundle'>;
}
declare module 'playwright/lib/transform/babelBundleImpl.js' {
  declare module.exports: $Exports<'playwright/lib/transform/babelBundleImpl'>;
}
declare module 'playwright/lib/transform/compilationCache.js' {
  declare module.exports: $Exports<'playwright/lib/transform/compilationCache'>;
}
declare module 'playwright/lib/transform/esmLoader.js' {
  declare module.exports: $Exports<'playwright/lib/transform/esmLoader'>;
}
declare module 'playwright/lib/transform/portTransport.js' {
  declare module.exports: $Exports<'playwright/lib/transform/portTransport'>;
}
declare module 'playwright/lib/transform/transform.js' {
  declare module.exports: $Exports<'playwright/lib/transform/transform'>;
}
declare module 'playwright/lib/util.js' {
  declare module.exports: $Exports<'playwright/lib/util'>;
}
declare module 'playwright/lib/utilsBundle.js' {
  declare module.exports: $Exports<'playwright/lib/utilsBundle'>;
}
declare module 'playwright/lib/utilsBundleImpl.js' {
  declare module.exports: $Exports<'playwright/lib/utilsBundleImpl'>;
}
declare module 'playwright/lib/worker/fixtureRunner.js' {
  declare module.exports: $Exports<'playwright/lib/worker/fixtureRunner'>;
}
declare module 'playwright/lib/worker/testInfo.js' {
  declare module.exports: $Exports<'playwright/lib/worker/testInfo'>;
}
declare module 'playwright/lib/worker/testTracing.js' {
  declare module.exports: $Exports<'playwright/lib/worker/testTracing'>;
}
declare module 'playwright/lib/worker/timeoutManager.js' {
  declare module.exports: $Exports<'playwright/lib/worker/timeoutManager'>;
}
declare module 'playwright/lib/worker/util.js' {
  declare module.exports: $Exports<'playwright/lib/worker/util'>;
}
declare module 'playwright/lib/worker/workerMain.js' {
  declare module.exports: $Exports<'playwright/lib/worker/workerMain'>;
}
declare module 'playwright/test.js' {
  declare module.exports: $Exports<'playwright/test'>;
}
