// flow-typed signature: 54956e2226443a4b634421fbdb5d8585
// flow-typed version: <<STUB>>/postcss-nesting_v^13.0.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-nesting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-nesting' {
  declare module.exports: any;
}
