/* eslint-disable flowtype/no-types-missing-file-annotation */
// flow-typed signature: b69b859633184c515d2b46ff4ad20a3f
// flow-typed version: <<STUB>>/postcss-value-parser_v^4.1.0/flow_v0.162.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-value-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type PostCSSValueASTNode =
  | {
      type: 'word' | 'unicode-range',
      value: string,
      sourceIndex: number,
    }
  | {
      type: 'string' | 'comment',
      value: string,
      quote: '"' | "'",
      sourceIndex: number,
      unclosed?: boolean,
    }
  | {
      type: 'comment',
      value: string,
      sourceIndex: number,
      unclosed?: boolean,
    }
  | {
      type: 'div',
      value: ',' | '/' | ':',
      sourceIndex: number,
      before: '' | ' ' | '  ' | '   ',
      after: '' | ' ' | '  ' | '   ',
    }
  | {
      type: 'space',
      value: ' ' | '  ' | '   ',
      sourceIndex: number,
    }
  | {
      type: 'function',
      value: string,
      before: '' | ' ' | '  ' | '   ',
      after: '' | ' ' | '  ' | '   ',
      nodes: Array<PostCSSValueASTNode>,
      unclosed?: boolean,
      sourceIndex: number,
    };

declare interface PostCSSValueAST {
  nodes: Array<PostCSSValueASTNode>;
  walk(
    callback: (PostCSSValueASTNode, number, PostCSSValueAST) => ?false,
    bubble?: boolean
  ): void;
}

type PostCSSValueParser = {
  (string): PostCSSValueAST,
  unit(string): { number: string, unit: string } | false,
  stringify(
    nodes: PostCSSValueAST | PostCSSValueASTNode,
    custom?: (PostCSSValueASTNode) => string
  ): string,
  walk(
    ast: PostCSSValueAST,
    callback: (PostCSSValueASTNode, number, PostCSSValueAST) => ?false,
    bubble?: boolean
  ): void,
};

declare module 'postcss-value-parser' {
  // eslint-disable-next-line flowtype/no-types-missing-file-annotation
  declare module.exports: PostCSSValueParser;
}
