// flow-typed signature: fdc8474da53396daf038ee44f7bd2071
// flow-typed version: <<STUB>>/postcss-loader_v^8.2.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'postcss-loader/dist' {
  declare module.exports: any;
}

declare module 'postcss-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-loader/dist/cjs.js' {
  declare module.exports: $Exports<'postcss-loader/dist/cjs'>;
}
declare module 'postcss-loader/dist/index' {
  declare module.exports: $Exports<'postcss-loader/dist'>;
}
declare module 'postcss-loader/dist/index.js' {
  declare module.exports: $Exports<'postcss-loader/dist'>;
}
declare module 'postcss-loader/dist/utils.js' {
  declare module.exports: $Exports<'postcss-loader/dist/utils'>;
}
