// flow-typed signature: c40576d848ac1e92d90dee235abb57de
// flow-typed version: <<STUB>>/react-codemirror2_v^7.3.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-codemirror2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-codemirror2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-codemirror2/index' {
  declare module.exports: $Exports<'react-codemirror2'>;
}
declare module 'react-codemirror2/index.js' {
  declare module.exports: $Exports<'react-codemirror2'>;
}
