// flow-typed signature: 8da72ddcad7e4657847e2bf9e76a2016
// flow-typed version: <<STUB>>/react-refresh_v^0.17.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-refresh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-refresh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-refresh/babel' {
  declare module.exports: any;
}

declare module 'react-refresh/cjs/react-refresh-babel.development' {
  declare module.exports: any;
}

declare module 'react-refresh/cjs/react-refresh-babel.production' {
  declare module.exports: any;
}

declare module 'react-refresh/cjs/react-refresh-runtime.development' {
  declare module.exports: any;
}

declare module 'react-refresh/cjs/react-refresh-runtime.production' {
  declare module.exports: any;
}

declare module 'react-refresh/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-refresh/babel.js' {
  declare module.exports: $Exports<'react-refresh/babel'>;
}
declare module 'react-refresh/cjs/react-refresh-babel.development.js' {
  declare module.exports: $Exports<'react-refresh/cjs/react-refresh-babel.development'>;
}
declare module 'react-refresh/cjs/react-refresh-babel.production.js' {
  declare module.exports: $Exports<'react-refresh/cjs/react-refresh-babel.production'>;
}
declare module 'react-refresh/cjs/react-refresh-runtime.development.js' {
  declare module.exports: $Exports<'react-refresh/cjs/react-refresh-runtime.development'>;
}
declare module 'react-refresh/cjs/react-refresh-runtime.production.js' {
  declare module.exports: $Exports<'react-refresh/cjs/react-refresh-runtime.production'>;
}
declare module 'react-refresh/runtime.js' {
  declare module.exports: $Exports<'react-refresh/runtime'>;
}
