// flow-typed signature: 44feb0a76976cb7abd46c09cd87c546b
// flow-typed version: <<STUB>>/rollup-plugin-jsx-remove-attributes_v^3.1.1/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-jsx-remove-attributes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-jsx-remove-attributes' {
  declare module.exports: any;
}
