// flow-typed signature: 9f93ca39639a5a22d0062ea19deaae7c
// flow-typed version: <<STUB>>/rollup-plugin-node-externals_v^8.1.1/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-externals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-node-externals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-node-externals/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-node-externals/dist/index' {
  declare module.exports: $Exports<'rollup-plugin-node-externals/dist'>;
}
declare module 'rollup-plugin-node-externals/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-node-externals/dist'>;
}
