/* eslint-disable flowtype/no-types-missing-file-annotation */
// flow-typed signature: 8f10de0a3c07be407ccd5876dd145a1c
// flow-typed version: <<STUB>>/rusha_v0.8.14/flow_v0.162.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rusha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rusha' {
  declare interface Hash {
    update(value: string | $ReadOnlyArray<number> | ArrayBuffer | Buffer): Hash;
    digest(encoding?: void): ArrayBuffer;
    digest(encoding: 'hex'): string;
  }

  declare interface RushaWorkerRequest {
    id: string;
    data: string | $ReadOnlyArray<number> | ArrayBuffer | Buffer | Blob;
  }

  declare interface RushaWorkerResponse {
    id: string;
    hash: string;
  }

  declare interface RushaWorker extends Worker {
    onmessage: null | ((res: MessageEvent) => mixed);
    postMessage(req: RushaWorkerRequest): void;
    terminate(): void;
  }

  declare interface Rusha {
    createHash(): Hash;
    createWorker(): RushaWorker;
    disableWorkerBehaviour(): void;
  }

  declare export default Rusha;
}
