// flow-typed signature: d00ccc3372b319f2e1f42b3854e35b94
// flow-typed version: <<STUB>>/scripts_v0.16.2/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scripts/flow-translator/flow-module-utils' {
  declare module.exports: any;
}

declare module 'scripts/flow-translator/generate-types' {
  declare module.exports: any;
}

declare module 'scripts/flow-translator/rewrite-imports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scripts/flow-translator/flow-module-utils.js' {
  declare module.exports: $Exports<'scripts/flow-translator/flow-module-utils'>;
}
declare module 'scripts/flow-translator/generate-types.js' {
  declare module.exports: $Exports<'scripts/flow-translator/generate-types'>;
}
declare module 'scripts/flow-translator/rewrite-imports.js' {
  declare module.exports: $Exports<'scripts/flow-translator/rewrite-imports'>;
}
