// flow-typed signature: cd5b2d1f88a2109d87031cd461e7e2eb
// flow-typed version: <<STUB>>/storybook_v^9.1.7/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook/dist/actions/decorator' {
  declare module.exports: any;
}

declare module 'storybook/dist/actions' {
  declare module.exports: any;
}

declare module 'storybook/dist/babel' {
  declare module.exports: any;
}

declare module 'storybook/dist/bin' {
  declare module.exports: any;
}

declare module 'storybook/dist/builder-manager' {
  declare module.exports: any;
}

declare module 'storybook/dist/channels' {
  declare module.exports: any;
}

declare module 'storybook/dist/cli/bin' {
  declare module.exports: any;
}

declare module 'storybook/dist/cli' {
  declare module.exports: any;
}

declare module 'storybook/dist/client-logger' {
  declare module.exports: any;
}

declare module 'storybook/dist/common' {
  declare module.exports: any;
}

declare module 'storybook/dist/components' {
  declare module.exports: any;
}

declare module 'storybook/dist/controls/decorator' {
  declare module.exports: any;
}

declare module 'storybook/dist/controls' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-events' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-server' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-server/presets/common-manager' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-server/presets/common-override-preset' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-server/presets/common-preset' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-server/presets/webpack/loaders/storybook-mock-transform-loader' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-server/presets/webpack/loaders/webpack-automock-loader' {
  declare module.exports: any;
}

declare module 'storybook/dist/csf-tools' {
  declare module.exports: any;
}

declare module 'storybook/dist/csf' {
  declare module.exports: any;
}

declare module 'storybook/dist/docs-tools' {
  declare module.exports: any;
}

declare module 'storybook/dist/highlight' {
  declare module.exports: any;
}

declare module 'storybook/dist' {
  declare module.exports: any;
}

declare module 'storybook/dist/instrumenter' {
  declare module.exports: any;
}

declare module 'storybook/dist/manager-api' {
  declare module.exports: any;
}

declare module 'storybook/dist/manager-errors' {
  declare module.exports: any;
}

declare module 'storybook/dist/manager/globals-module-info' {
  declare module.exports: any;
}

declare module 'storybook/dist/manager/globals-runtime' {
  declare module.exports: any;
}

declare module 'storybook/dist/manager/globals' {
  declare module.exports: any;
}

declare module 'storybook/dist/manager/runtime' {
  declare module.exports: any;
}

declare module 'storybook/dist/node-logger' {
  declare module.exports: any;
}

declare module 'storybook/dist/preview-api' {
  declare module.exports: any;
}

declare module 'storybook/dist/preview-errors' {
  declare module.exports: any;
}

declare module 'storybook/dist/preview/globals' {
  declare module.exports: any;
}

declare module 'storybook/dist/preview/runtime' {
  declare module.exports: any;
}

declare module 'storybook/dist/router' {
  declare module.exports: any;
}

declare module 'storybook/dist/server-errors' {
  declare module.exports: any;
}

declare module 'storybook/dist/telemetry' {
  declare module.exports: any;
}

declare module 'storybook/dist/test' {
  declare module.exports: any;
}

declare module 'storybook/dist/theming/create' {
  declare module.exports: any;
}

declare module 'storybook/dist/theming' {
  declare module.exports: any;
}

declare module 'storybook/dist/types' {
  declare module.exports: any;
}

declare module 'storybook/dist/viewport' {
  declare module.exports: any;
}

declare module 'storybook/templates/mocker-runtime.template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook/dist/actions/decorator.js' {
  declare module.exports: $Exports<'storybook/dist/actions/decorator'>;
}
declare module 'storybook/dist/actions/index' {
  declare module.exports: $Exports<'storybook/dist/actions'>;
}
declare module 'storybook/dist/actions/index.js' {
  declare module.exports: $Exports<'storybook/dist/actions'>;
}
declare module 'storybook/dist/babel/index' {
  declare module.exports: $Exports<'storybook/dist/babel'>;
}
declare module 'storybook/dist/babel/index.js' {
  declare module.exports: $Exports<'storybook/dist/babel'>;
}
declare module 'storybook/dist/bin/index' {
  declare module.exports: $Exports<'storybook/dist/bin'>;
}
declare module 'storybook/dist/bin/index.js' {
  declare module.exports: $Exports<'storybook/dist/bin'>;
}
declare module 'storybook/dist/builder-manager/index' {
  declare module.exports: $Exports<'storybook/dist/builder-manager'>;
}
declare module 'storybook/dist/builder-manager/index.js' {
  declare module.exports: $Exports<'storybook/dist/builder-manager'>;
}
declare module 'storybook/dist/channels/index' {
  declare module.exports: $Exports<'storybook/dist/channels'>;
}
declare module 'storybook/dist/channels/index.js' {
  declare module.exports: $Exports<'storybook/dist/channels'>;
}
declare module 'storybook/dist/cli/bin/index' {
  declare module.exports: $Exports<'storybook/dist/cli/bin'>;
}
declare module 'storybook/dist/cli/bin/index.js' {
  declare module.exports: $Exports<'storybook/dist/cli/bin'>;
}
declare module 'storybook/dist/cli/index' {
  declare module.exports: $Exports<'storybook/dist/cli'>;
}
declare module 'storybook/dist/cli/index.js' {
  declare module.exports: $Exports<'storybook/dist/cli'>;
}
declare module 'storybook/dist/client-logger/index' {
  declare module.exports: $Exports<'storybook/dist/client-logger'>;
}
declare module 'storybook/dist/client-logger/index.js' {
  declare module.exports: $Exports<'storybook/dist/client-logger'>;
}
declare module 'storybook/dist/common/index' {
  declare module.exports: $Exports<'storybook/dist/common'>;
}
declare module 'storybook/dist/common/index.js' {
  declare module.exports: $Exports<'storybook/dist/common'>;
}
declare module 'storybook/dist/components/index' {
  declare module.exports: $Exports<'storybook/dist/components'>;
}
declare module 'storybook/dist/components/index.js' {
  declare module.exports: $Exports<'storybook/dist/components'>;
}
declare module 'storybook/dist/controls/decorator.js' {
  declare module.exports: $Exports<'storybook/dist/controls/decorator'>;
}
declare module 'storybook/dist/controls/index' {
  declare module.exports: $Exports<'storybook/dist/controls'>;
}
declare module 'storybook/dist/controls/index.js' {
  declare module.exports: $Exports<'storybook/dist/controls'>;
}
declare module 'storybook/dist/core-events/index' {
  declare module.exports: $Exports<'storybook/dist/core-events'>;
}
declare module 'storybook/dist/core-events/index.js' {
  declare module.exports: $Exports<'storybook/dist/core-events'>;
}
declare module 'storybook/dist/core-server/index' {
  declare module.exports: $Exports<'storybook/dist/core-server'>;
}
declare module 'storybook/dist/core-server/index.js' {
  declare module.exports: $Exports<'storybook/dist/core-server'>;
}
declare module 'storybook/dist/core-server/presets/common-manager.js' {
  declare module.exports: $Exports<'storybook/dist/core-server/presets/common-manager'>;
}
declare module 'storybook/dist/core-server/presets/common-override-preset.js' {
  declare module.exports: $Exports<'storybook/dist/core-server/presets/common-override-preset'>;
}
declare module 'storybook/dist/core-server/presets/common-preset.js' {
  declare module.exports: $Exports<'storybook/dist/core-server/presets/common-preset'>;
}
declare module 'storybook/dist/core-server/presets/webpack/loaders/storybook-mock-transform-loader.js' {
  declare module.exports: $Exports<'storybook/dist/core-server/presets/webpack/loaders/storybook-mock-transform-loader'>;
}
declare module 'storybook/dist/core-server/presets/webpack/loaders/webpack-automock-loader.js' {
  declare module.exports: $Exports<'storybook/dist/core-server/presets/webpack/loaders/webpack-automock-loader'>;
}
declare module 'storybook/dist/csf-tools/index' {
  declare module.exports: $Exports<'storybook/dist/csf-tools'>;
}
declare module 'storybook/dist/csf-tools/index.js' {
  declare module.exports: $Exports<'storybook/dist/csf-tools'>;
}
declare module 'storybook/dist/csf/index' {
  declare module.exports: $Exports<'storybook/dist/csf'>;
}
declare module 'storybook/dist/csf/index.js' {
  declare module.exports: $Exports<'storybook/dist/csf'>;
}
declare module 'storybook/dist/docs-tools/index' {
  declare module.exports: $Exports<'storybook/dist/docs-tools'>;
}
declare module 'storybook/dist/docs-tools/index.js' {
  declare module.exports: $Exports<'storybook/dist/docs-tools'>;
}
declare module 'storybook/dist/highlight/index' {
  declare module.exports: $Exports<'storybook/dist/highlight'>;
}
declare module 'storybook/dist/highlight/index.js' {
  declare module.exports: $Exports<'storybook/dist/highlight'>;
}
declare module 'storybook/dist/index' {
  declare module.exports: $Exports<'storybook/dist'>;
}
declare module 'storybook/dist/index.js' {
  declare module.exports: $Exports<'storybook/dist'>;
}
declare module 'storybook/dist/instrumenter/index' {
  declare module.exports: $Exports<'storybook/dist/instrumenter'>;
}
declare module 'storybook/dist/instrumenter/index.js' {
  declare module.exports: $Exports<'storybook/dist/instrumenter'>;
}
declare module 'storybook/dist/manager-api/index' {
  declare module.exports: $Exports<'storybook/dist/manager-api'>;
}
declare module 'storybook/dist/manager-api/index.js' {
  declare module.exports: $Exports<'storybook/dist/manager-api'>;
}
declare module 'storybook/dist/manager-errors.js' {
  declare module.exports: $Exports<'storybook/dist/manager-errors'>;
}
declare module 'storybook/dist/manager/globals-module-info.js' {
  declare module.exports: $Exports<'storybook/dist/manager/globals-module-info'>;
}
declare module 'storybook/dist/manager/globals-runtime.js' {
  declare module.exports: $Exports<'storybook/dist/manager/globals-runtime'>;
}
declare module 'storybook/dist/manager/globals.js' {
  declare module.exports: $Exports<'storybook/dist/manager/globals'>;
}
declare module 'storybook/dist/manager/runtime.js' {
  declare module.exports: $Exports<'storybook/dist/manager/runtime'>;
}
declare module 'storybook/dist/node-logger/index' {
  declare module.exports: $Exports<'storybook/dist/node-logger'>;
}
declare module 'storybook/dist/node-logger/index.js' {
  declare module.exports: $Exports<'storybook/dist/node-logger'>;
}
declare module 'storybook/dist/preview-api/index' {
  declare module.exports: $Exports<'storybook/dist/preview-api'>;
}
declare module 'storybook/dist/preview-api/index.js' {
  declare module.exports: $Exports<'storybook/dist/preview-api'>;
}
declare module 'storybook/dist/preview-errors.js' {
  declare module.exports: $Exports<'storybook/dist/preview-errors'>;
}
declare module 'storybook/dist/preview/globals.js' {
  declare module.exports: $Exports<'storybook/dist/preview/globals'>;
}
declare module 'storybook/dist/preview/runtime.js' {
  declare module.exports: $Exports<'storybook/dist/preview/runtime'>;
}
declare module 'storybook/dist/router/index' {
  declare module.exports: $Exports<'storybook/dist/router'>;
}
declare module 'storybook/dist/router/index.js' {
  declare module.exports: $Exports<'storybook/dist/router'>;
}
declare module 'storybook/dist/server-errors.js' {
  declare module.exports: $Exports<'storybook/dist/server-errors'>;
}
declare module 'storybook/dist/telemetry/index' {
  declare module.exports: $Exports<'storybook/dist/telemetry'>;
}
declare module 'storybook/dist/telemetry/index.js' {
  declare module.exports: $Exports<'storybook/dist/telemetry'>;
}
declare module 'storybook/dist/test/index' {
  declare module.exports: $Exports<'storybook/dist/test'>;
}
declare module 'storybook/dist/test/index.js' {
  declare module.exports: $Exports<'storybook/dist/test'>;
}
declare module 'storybook/dist/theming/create.js' {
  declare module.exports: $Exports<'storybook/dist/theming/create'>;
}
declare module 'storybook/dist/theming/index' {
  declare module.exports: $Exports<'storybook/dist/theming'>;
}
declare module 'storybook/dist/theming/index.js' {
  declare module.exports: $Exports<'storybook/dist/theming'>;
}
declare module 'storybook/dist/types/index' {
  declare module.exports: $Exports<'storybook/dist/types'>;
}
declare module 'storybook/dist/types/index.js' {
  declare module.exports: $Exports<'storybook/dist/types'>;
}
declare module 'storybook/dist/viewport/index' {
  declare module.exports: $Exports<'storybook/dist/viewport'>;
}
declare module 'storybook/dist/viewport/index.js' {
  declare module.exports: $Exports<'storybook/dist/viewport'>;
}
declare module 'storybook/templates/mocker-runtime.template.js' {
  declare module.exports: $Exports<'storybook/templates/mocker-runtime.template'>;
}
