// flow-typed signature: 7869429013775dcf3079d5e4767eb916
// flow-typed version: <<STUB>>/styled-jsx_v^5.1.1/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-jsx' {
  declare module.exports: any;
}
