// flow-typed signature: 903af64d97c6f726ed47a3db1a19ff6b
// flow-typed version: <<STUB>>/styleq_v0.2.1/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styleq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styleq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styleq/dist/styleq' {
  declare module.exports: any;
}

declare module 'styleq/styleq' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styleq/dist/styleq.js' {
  declare module.exports: $Exports<'styleq/dist/styleq'>;
}
declare module 'styleq/styleq.js' {
  declare module.exports: $Exports<'styleq/styleq'>;
}
