// flow-typed signature: 1934a45faf555f7fc017676fc54f1315
// flow-typed version: <<STUB>>/typescript-eslint_v^8.44.0/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript-eslint/dist/compatibility-types' {
  declare module.exports: any;
}

declare module 'typescript-eslint/dist/config-helper' {
  declare module.exports: any;
}

declare module 'typescript-eslint/dist/getTSConfigRootDirFromStack' {
  declare module.exports: any;
}

declare module 'typescript-eslint/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript-eslint/dist/compatibility-types.js' {
  declare module.exports: $Exports<'typescript-eslint/dist/compatibility-types'>;
}
declare module 'typescript-eslint/dist/config-helper.js' {
  declare module.exports: $Exports<'typescript-eslint/dist/config-helper'>;
}
declare module 'typescript-eslint/dist/getTSConfigRootDirFromStack.js' {
  declare module.exports: $Exports<'typescript-eslint/dist/getTSConfigRootDirFromStack'>;
}
declare module 'typescript-eslint/dist/index' {
  declare module.exports: $Exports<'typescript-eslint/dist'>;
}
declare module 'typescript-eslint/dist/index.js' {
  declare module.exports: $Exports<'typescript-eslint/dist'>;
}
