// flow-typed signature: 39d7b86987ac88d179161fe9a76e88ad
// flow-typed version: <<STUB>>/typescript_v^5.3.3/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript/lib/_tsc' {
  declare module.exports: any;
}

declare module 'typescript/lib/_tsserver' {
  declare module.exports: any;
}

declare module 'typescript/lib/_typingsInstaller' {
  declare module.exports: any;
}

declare module 'typescript/lib/tsc' {
  declare module.exports: any;
}

declare module 'typescript/lib/tsserver' {
  declare module.exports: any;
}

declare module 'typescript/lib/tsserverlibrary' {
  declare module.exports: any;
}

declare module 'typescript/lib/typescript' {
  declare module.exports: any;
}

declare module 'typescript/lib/typingsInstaller' {
  declare module.exports: any;
}

declare module 'typescript/lib/watchGuard' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript/lib/_tsc.js' {
  declare module.exports: $Exports<'typescript/lib/_tsc'>;
}
declare module 'typescript/lib/_tsserver.js' {
  declare module.exports: $Exports<'typescript/lib/_tsserver'>;
}
declare module 'typescript/lib/_typingsInstaller.js' {
  declare module.exports: $Exports<'typescript/lib/_typingsInstaller'>;
}
declare module 'typescript/lib/tsc.js' {
  declare module.exports: $Exports<'typescript/lib/tsc'>;
}
declare module 'typescript/lib/tsserver.js' {
  declare module.exports: $Exports<'typescript/lib/tsserver'>;
}
declare module 'typescript/lib/tsserverlibrary.js' {
  declare module.exports: $Exports<'typescript/lib/tsserverlibrary'>;
}
declare module 'typescript/lib/typescript.js' {
  declare module.exports: $Exports<'typescript/lib/typescript'>;
}
declare module 'typescript/lib/typingsInstaller.js' {
  declare module.exports: $Exports<'typescript/lib/typingsInstaller'>;
}
declare module 'typescript/lib/watchGuard.js' {
  declare module.exports: $Exports<'typescript/lib/watchGuard'>;
}
