// flow-typed signature: abe355eff5114103c0777a18a784dc29
// flow-typed version: <<STUB>>/vite-plugin-dts_v^4.5.4/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-dts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-dts' {
  declare module.exports: any;
}
