// flow-typed signature: 688faf38fa73804b8503504f9c6955b3
// flow-typed version: <<STUB>>/vitest_v^3.2.4/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vitest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vitest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vitest/dist/browser' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/_commonjsHelpers.BFTU3MAI' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/base.DfmxU-tU' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/benchmark.CYdenmiT' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/cac.Cb-PYCCB' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/cli-api.BkDphVBG' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/console.CtFJOzRO' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/constants.DnKduX2e' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/coverage.DL5VHqXY' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/coverage.DVF1vEu8' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/creator.GK6I-cL4' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/date.Bq6ZW5rf' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/defaults.B7q_naMc' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/env.D4Lgay0q' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/execute.B7h3T_Hc' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/git.BVQ8w_Sw' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/globals.DEHgCU4V' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.B521nVV-' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.BCWujgDG' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.CdQS2e2Q' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.CmSc2RE5' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.CwejwG0H' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.D3XRDfWc' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.VByaPkjc' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/index.X0nbfr6-' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/inspector.C914Efll' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/node.fjCdwEIl' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/rpc.-pEldfrD' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/runBaseTests.9Ij9_de-' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/setup-common.Dd054P77' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/typechecker.DRKU1-1g' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/utils.CAioKnHs' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/utils.XdZDrNZV' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/vi.bdSIJ99Y' {
  declare module.exports: any;
}

declare module 'vitest/dist/chunks/vm.BThCzidc' {
  declare module.exports: any;
}

declare module 'vitest/dist/cli' {
  declare module.exports: any;
}

declare module 'vitest/dist/config' {
  declare module.exports: any;
}

declare module 'vitest/dist/coverage' {
  declare module.exports: any;
}

declare module 'vitest/dist/environments' {
  declare module.exports: any;
}

declare module 'vitest/dist/execute' {
  declare module.exports: any;
}

declare module 'vitest/dist' {
  declare module.exports: any;
}

declare module 'vitest/dist/mocker' {
  declare module.exports: any;
}

declare module 'vitest/dist/node' {
  declare module.exports: any;
}

declare module 'vitest/dist/path' {
  declare module.exports: any;
}

declare module 'vitest/dist/reporters' {
  declare module.exports: any;
}

declare module 'vitest/dist/runners' {
  declare module.exports: any;
}

declare module 'vitest/dist/snapshot' {
  declare module.exports: any;
}

declare module 'vitest/dist/spy' {
  declare module.exports: any;
}

declare module 'vitest/dist/suite' {
  declare module.exports: any;
}

declare module 'vitest/dist/worker' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/forks' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/runVmTests' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/threads' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/vmForks' {
  declare module.exports: any;
}

declare module 'vitest/dist/workers/vmThreads' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vitest/dist/browser.js' {
  declare module.exports: $Exports<'vitest/dist/browser'>;
}
declare module 'vitest/dist/chunks/_commonjsHelpers.BFTU3MAI.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/_commonjsHelpers.BFTU3MAI'>;
}
declare module 'vitest/dist/chunks/base.DfmxU-tU.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/base.DfmxU-tU'>;
}
declare module 'vitest/dist/chunks/benchmark.CYdenmiT.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/benchmark.CYdenmiT'>;
}
declare module 'vitest/dist/chunks/cac.Cb-PYCCB.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/cac.Cb-PYCCB'>;
}
declare module 'vitest/dist/chunks/cli-api.BkDphVBG.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/cli-api.BkDphVBG'>;
}
declare module 'vitest/dist/chunks/console.CtFJOzRO.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/console.CtFJOzRO'>;
}
declare module 'vitest/dist/chunks/constants.DnKduX2e.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/constants.DnKduX2e'>;
}
declare module 'vitest/dist/chunks/coverage.DL5VHqXY.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/coverage.DL5VHqXY'>;
}
declare module 'vitest/dist/chunks/coverage.DVF1vEu8.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/coverage.DVF1vEu8'>;
}
declare module 'vitest/dist/chunks/creator.GK6I-cL4.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/creator.GK6I-cL4'>;
}
declare module 'vitest/dist/chunks/date.Bq6ZW5rf.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/date.Bq6ZW5rf'>;
}
declare module 'vitest/dist/chunks/defaults.B7q_naMc.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/defaults.B7q_naMc'>;
}
declare module 'vitest/dist/chunks/env.D4Lgay0q.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/env.D4Lgay0q'>;
}
declare module 'vitest/dist/chunks/execute.B7h3T_Hc.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/execute.B7h3T_Hc'>;
}
declare module 'vitest/dist/chunks/git.BVQ8w_Sw.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/git.BVQ8w_Sw'>;
}
declare module 'vitest/dist/chunks/globals.DEHgCU4V.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/globals.DEHgCU4V'>;
}
declare module 'vitest/dist/chunks/index.B521nVV-.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.B521nVV-'>;
}
declare module 'vitest/dist/chunks/index.BCWujgDG.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.BCWujgDG'>;
}
declare module 'vitest/dist/chunks/index.CdQS2e2Q.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.CdQS2e2Q'>;
}
declare module 'vitest/dist/chunks/index.CmSc2RE5.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.CmSc2RE5'>;
}
declare module 'vitest/dist/chunks/index.CwejwG0H.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.CwejwG0H'>;
}
declare module 'vitest/dist/chunks/index.D3XRDfWc.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.D3XRDfWc'>;
}
declare module 'vitest/dist/chunks/index.VByaPkjc.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.VByaPkjc'>;
}
declare module 'vitest/dist/chunks/index.X0nbfr6-.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/index.X0nbfr6-'>;
}
declare module 'vitest/dist/chunks/inspector.C914Efll.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/inspector.C914Efll'>;
}
declare module 'vitest/dist/chunks/node.fjCdwEIl.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/node.fjCdwEIl'>;
}
declare module 'vitest/dist/chunks/rpc.-pEldfrD.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/rpc.-pEldfrD'>;
}
declare module 'vitest/dist/chunks/runBaseTests.9Ij9_de-.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/runBaseTests.9Ij9_de-'>;
}
declare module 'vitest/dist/chunks/setup-common.Dd054P77.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/setup-common.Dd054P77'>;
}
declare module 'vitest/dist/chunks/typechecker.DRKU1-1g.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/typechecker.DRKU1-1g'>;
}
declare module 'vitest/dist/chunks/utils.CAioKnHs.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/utils.CAioKnHs'>;
}
declare module 'vitest/dist/chunks/utils.XdZDrNZV.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/utils.XdZDrNZV'>;
}
declare module 'vitest/dist/chunks/vi.bdSIJ99Y.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/vi.bdSIJ99Y'>;
}
declare module 'vitest/dist/chunks/vm.BThCzidc.js' {
  declare module.exports: $Exports<'vitest/dist/chunks/vm.BThCzidc'>;
}
declare module 'vitest/dist/cli.js' {
  declare module.exports: $Exports<'vitest/dist/cli'>;
}
declare module 'vitest/dist/config.js' {
  declare module.exports: $Exports<'vitest/dist/config'>;
}
declare module 'vitest/dist/coverage.js' {
  declare module.exports: $Exports<'vitest/dist/coverage'>;
}
declare module 'vitest/dist/environments.js' {
  declare module.exports: $Exports<'vitest/dist/environments'>;
}
declare module 'vitest/dist/execute.js' {
  declare module.exports: $Exports<'vitest/dist/execute'>;
}
declare module 'vitest/dist/index' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/index.js' {
  declare module.exports: $Exports<'vitest/dist'>;
}
declare module 'vitest/dist/mocker.js' {
  declare module.exports: $Exports<'vitest/dist/mocker'>;
}
declare module 'vitest/dist/node.js' {
  declare module.exports: $Exports<'vitest/dist/node'>;
}
declare module 'vitest/dist/path.js' {
  declare module.exports: $Exports<'vitest/dist/path'>;
}
declare module 'vitest/dist/reporters.js' {
  declare module.exports: $Exports<'vitest/dist/reporters'>;
}
declare module 'vitest/dist/runners.js' {
  declare module.exports: $Exports<'vitest/dist/runners'>;
}
declare module 'vitest/dist/snapshot.js' {
  declare module.exports: $Exports<'vitest/dist/snapshot'>;
}
declare module 'vitest/dist/spy.js' {
  declare module.exports: $Exports<'vitest/dist/spy'>;
}
declare module 'vitest/dist/suite.js' {
  declare module.exports: $Exports<'vitest/dist/suite'>;
}
declare module 'vitest/dist/worker.js' {
  declare module.exports: $Exports<'vitest/dist/worker'>;
}
declare module 'vitest/dist/workers.js' {
  declare module.exports: $Exports<'vitest/dist/workers'>;
}
declare module 'vitest/dist/workers/forks.js' {
  declare module.exports: $Exports<'vitest/dist/workers/forks'>;
}
declare module 'vitest/dist/workers/runVmTests.js' {
  declare module.exports: $Exports<'vitest/dist/workers/runVmTests'>;
}
declare module 'vitest/dist/workers/threads.js' {
  declare module.exports: $Exports<'vitest/dist/workers/threads'>;
}
declare module 'vitest/dist/workers/vmForks.js' {
  declare module.exports: $Exports<'vitest/dist/workers/vmForks'>;
}
declare module 'vitest/dist/workers/vmThreads.js' {
  declare module.exports: $Exports<'vitest/dist/workers/vmThreads'>;
}
