// flow-typed signature: c6cfede9e6a92f619d47fc943d6e0279
// flow-typed version: <<STUB>>/webpack-cli_v^5.1.4/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/bootstrap' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/plugins/cli-plugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/types' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/dynamic-import-loader' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/webpack-cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cli/bin/cli.js' {
  declare module.exports: $Exports<'webpack-cli/bin/cli'>;
}
declare module 'webpack-cli/lib/bootstrap.js' {
  declare module.exports: $Exports<'webpack-cli/lib/bootstrap'>;
}
declare module 'webpack-cli/lib/index' {
  declare module.exports: $Exports<'webpack-cli/lib'>;
}
declare module 'webpack-cli/lib/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib'>;
}
declare module 'webpack-cli/lib/plugins/cli-plugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/plugins/cli-plugin'>;
}
declare module 'webpack-cli/lib/types.js' {
  declare module.exports: $Exports<'webpack-cli/lib/types'>;
}
declare module 'webpack-cli/lib/utils/dynamic-import-loader.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/dynamic-import-loader'>;
}
declare module 'webpack-cli/lib/webpack-cli.js' {
  declare module.exports: $Exports<'webpack-cli/lib/webpack-cli'>;
}
