// flow-typed signature: fc80f25c9b1e988e3f4b81e3a815084d
// flow-typed version: <<STUB>>/@chromatic-com/storybook_v^4.1.1/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chromatic-com/storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chromatic-com/storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chromatic-com/storybook/dist' {
  declare module.exports: any;
}

declare module '@chromatic-com/storybook/dist/preset' {
  declare module.exports: any;
}

declare module '@chromatic-com/storybook/preset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chromatic-com/storybook/dist/index' {
  declare module.exports: $Exports<'@chromatic-com/storybook/dist'>;
}
declare module '@chromatic-com/storybook/dist/index.js' {
  declare module.exports: $Exports<'@chromatic-com/storybook/dist'>;
}
declare module '@chromatic-com/storybook/dist/preset.js' {
  declare module.exports: $Exports<'@chromatic-com/storybook/dist/preset'>;
}
declare module '@chromatic-com/storybook/preset.js' {
  declare module.exports: $Exports<'@chromatic-com/storybook/preset'>;
}
