// flow-typed signature: b5bf446e39c9e2ea5a2a3154e591024b
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.26.8/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
