// flow-typed signature: 5c0f6b90dc86ce235b2d85d9018ad9ea
// flow-typed version: <<STUB>>/@babel/node_v^7.23.9/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/node/bin/babel-node' {
  declare module.exports: any;
}

declare module '@babel/node/lib/_babel-node' {
  declare module.exports: any;
}

declare module '@babel/node/lib/babel-node' {
  declare module.exports: any;
}

declare module '@babel/node/lib/program-setup' {
  declare module.exports: any;
}

declare module '@babel/node/lib/split-args' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/node/bin/babel-node.js' {
  declare module.exports: $Exports<'@babel/node/bin/babel-node'>;
}
declare module '@babel/node/lib/_babel-node.js' {
  declare module.exports: $Exports<'@babel/node/lib/_babel-node'>;
}
declare module '@babel/node/lib/babel-node.js' {
  declare module.exports: $Exports<'@babel/node/lib/babel-node'>;
}
declare module '@babel/node/lib/program-setup.js' {
  declare module.exports: $Exports<'@babel/node/lib/program-setup'>;
}
declare module '@babel/node/lib/split-args.js' {
  declare module.exports: $Exports<'@babel/node/lib/split-args'>;
}
