// flow-typed signature: 524045d2665275c4a9d50b585bef8161
// flow-typed version: <<STUB>>/@babel/preset-env_v^7.28.3/flow_v0.267.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-env/data/built-in-modules' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/built-in-modules.json' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/built-ins' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/built-ins.json' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/core-js-compat' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/corejs2-built-ins' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/corejs2-built-ins.json' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/plugins' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/plugins.json' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/shipped-proposals' {
  declare module.exports: any;
}

declare module '@babel/preset-env/data/unreleased-labels' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/available-plugins' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/debug' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/filter-items' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/module-transformations' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/normalize-options' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/options' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/plugins-compat-data' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/shipped-proposals' {
  declare module.exports: any;
}

declare module '@babel/preset-env/lib/targets-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-env/data/built-in-modules.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/built-in-modules'>;
}
declare module '@babel/preset-env/data/built-in-modules.json.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/built-in-modules.json'>;
}
declare module '@babel/preset-env/data/built-ins.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/built-ins'>;
}
declare module '@babel/preset-env/data/built-ins.json.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/built-ins.json'>;
}
declare module '@babel/preset-env/data/core-js-compat.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/core-js-compat'>;
}
declare module '@babel/preset-env/data/corejs2-built-ins.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/corejs2-built-ins'>;
}
declare module '@babel/preset-env/data/corejs2-built-ins.json.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/corejs2-built-ins.json'>;
}
declare module '@babel/preset-env/data/plugins.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/plugins'>;
}
declare module '@babel/preset-env/data/plugins.json.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/plugins.json'>;
}
declare module '@babel/preset-env/data/shipped-proposals.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/shipped-proposals'>;
}
declare module '@babel/preset-env/data/unreleased-labels.js' {
  declare module.exports: $Exports<'@babel/preset-env/data/unreleased-labels'>;
}
declare module '@babel/preset-env/lib/available-plugins.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/available-plugins'>;
}
declare module '@babel/preset-env/lib/debug.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/debug'>;
}
declare module '@babel/preset-env/lib/filter-items.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/filter-items'>;
}
declare module '@babel/preset-env/lib/index' {
  declare module.exports: $Exports<'@babel/preset-env/lib'>;
}
declare module '@babel/preset-env/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib'>;
}
declare module '@babel/preset-env/lib/module-transformations.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/module-transformations'>;
}
declare module '@babel/preset-env/lib/normalize-options.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/normalize-options'>;
}
declare module '@babel/preset-env/lib/options.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/options'>;
}
declare module '@babel/preset-env/lib/plugins-compat-data.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/plugins-compat-data'>;
}
declare module '@babel/preset-env/lib/shipped-proposals.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/shipped-proposals'>;
}
declare module '@babel/preset-env/lib/targets-parser.js' {
  declare module.exports: $Exports<'@babel/preset-env/lib/targets-parser'>;
}
