name: Feature request
description: If you have a suggestion…
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the feature request
      description: Please provide a concise description of the request, potential solutions, and additional context.
    validations:
      required: true
