/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 */

import './globals.css';
import { globalTokens as $ } from './globalTokens.stylex';
import * as stylex from '@stylexjs/stylex';
import '../stylex_bundle.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html
      {...{
        className: 'x108lcm5 x1us19tq x1ghz6dp x1717udv',
      }}
      lang="en"
    >
      <body
        {...{
          className: 'x1us19tq x1ghz6dp x1717udv xuoex8v xopeh9 xjml5my',
        }}
      >
        {children}
      </body>
    </html>
  );
}
const DARK = '@media (prefers-color-scheme: dark)';
