[files]
extend-exclude = [
  "*.snap",
  "flow-typed/*",
  # Too many false positives on inline snapshots
  "packages/**/__tests__/",
  # Fixture data has lots of typos
  "packages/benchmarks/**/fixtures/",
]

[default.extend-words]
# Ignore false-positives
stylex = "stylex"
